### PR TITLE
Add Graaf

### PR DESCRIPTION
**Pull request by Angelmmiguel**
Graaf provides designers pure CSS grid overlays. You can use them to check the position of the elements in your design prototype. It doesn't require any HTML boilerplate, you only need to link the stylesheet that fits your grid system:

```
<link rel="stylesheet" href="https://grids.graaf.space/WIDTH/COLUMNS/GUTTER.css">
<link rel="stylesheet" href="https://grids.graaf.space/793/10/16.css">
<link rel="stylesheet" href="https://grids.graaf.space/graff.css">
<link rel="stylesheet" href="https://grids.graaf.space/medium.css">
...
```

The result:

Graaf.space

### CODE REVIEW

**Comment by Angelmmiguel** [comment]
I checked the Travis build and it seems it's failing for other project:

```
1. [L175]  http://stocky.pro/ getaddrinfo: Name or service not known 
```

Should I remove it in my PR? Thanks!

**Comment by gztchan** [comment]
you can rebase master first to remove those unavailable resources.

**Comment by Angelmmiguel** [comment]
Hello @gztchan,

I rebased master branch but there is another link that fails in the tests. However, the site is online now. 

```
1. [L431] 502 http://manualcreative.com/project/nike-pro-services/  
```

Thanks!

**Comment by gztchan** [comment]
Graaf will not be added into the list, because it can not be considered as Application.

**Pull request closed without merging**
