### PR TITLE
Including Affinity Designer in tools

### PR DESCRIPTION
**Pull request by romuloalves**
Including Affinity Designer, a professional graphic design software for Mac, in tools category.

### CODE REVIEW

**Comment by gztchan** [comment]
This is definitely awesome!!!

**Comment by romuloalves** [comment]
😎

**Comment by mineiro** [comment]
They are providing a beta for Windows too! https://affinity.serif.com/en-gb/windows/

**Comment by gztchan** [comment]
@mineiro 👍  Windows run "slowly", but finally arrive , haha

**Pull request merged**
